import type { Bilingual } from './site';

export interface GlossaryTerm {
  term: Bilingual;
  definition: Bilingual;
}

const g = (
  termTr: string,
  termEn: string,
  defTr: string,
  defEn: string,
): GlossaryTerm => ({
  term: { tr: termTr, en: termEn },
  definition: { tr: defTr, en: defEn },
});

export const GLOSSARY: GlossaryTerm[] = [
  g(
    'Fondan',
    'Fondant',
    'Pastaya pürüzsüz, kusursuz bir yüzey kazandıran, açılabilir şekerli hamur kaplama.',
    'A rollable sugar paste that gives the cake a smooth, flawless surface.',
  ),
  g(
    'Ganaj',
    'Ganache',
    'Çikolata ve kremanın eritilerek karıştırılmasıyla elde edilen, parlak ve yoğun kaplama.',
    'A glossy, rich coating made by melting and blending chocolate with cream.',
  ),
  g(
    'Tereyağlı Krema',
    'Buttercream',
    'Tereyağı ve pudra şekeriyle hazırlanan, yumuşak ve lezzetli klasik kaplama.',
    'A soft, flavourful classic frosting made with butter and icing sugar.',
  ),
  g(
    'Pandispanya',
    'Sponge',
    'Pastanın temel katmanını oluşturan hafif ve hava dolu kek tabanı.',
    'The light, airy cake base that forms the foundation of the cake.',
  ),
  g(
    'Drip Efekti',
    'Drip Effect',
    'Pastanın üst kenarından aşağı doğru akıtılan çikolata veya şeker süslemesi.',
    'A chocolate or sugar decoration dripped down from the top edge of the cake.',
  ),
  g(
    'Naked Cake',
    'Naked Cake',
    'Kenarları minimum kremayla kaplanan, katmanların göründüğü doğal görünümlü pasta.',
    'A natural-looking cake with minimal frosting on the sides, revealing the layers.',
  ),
  g(
    'Topper',
    'Topper',
    'Pastanın en üstüne yerleştirilen dekoratif süs öğesi.',
    'A decorative ornament placed on top of the cake.',
  ),
  g(
    'Sahte Kat (Dummy)',
    'Dummy Tier',
    'Görsel ihtişam için kullanılan, köpükten yapılma yenmeyen pasta katı.',
    'A non-edible foam tier used to add visual grandeur.',
  ),
  g(
    'Şeker Çiçeği',
    'Sugar Flower',
    'Tamamen yenilebilir şekerden elle yapılan gerçekçi çiçek süslemeleri.',
    'Realistic flower decorations handcrafted entirely from edible sugar.',
  ),
  g(
    'Yenilebilir Baskı',
    'Edible Print',
    'Gıda boyalarıyla yenilebilir kâğıda basılan logo veya görseller.',
    'Logos or images printed on edible paper with food-safe inks.',
  ),
  g(
    'Kuvertür',
    'Couverture',
    'Yüksek kakao yağı oranına sahip, profesyonel kalitede çikolata.',
    'Professional-grade chocolate with a high cocoa-butter content.',
  ),
  g(
    'Mascarpone',
    'Mascarpone',
    'İtalyan kökenli, kremamsı ve hafif tatlı bir taze peynir.',
    'A creamy, mildly sweet fresh cheese of Italian origin.',
  ),
  g(
    'Labne Kreması',
    'Cream Cheese Frosting',
    'Red velvet gibi pastalarda kullanılan, hafif ekşi ve kremsi kaplama.',
    'A slightly tangy, creamy frosting used on cakes like red velvet.',
  ),
  g(
    'Şurup',
    'Soak / Syrup',
    'Pandispanyayı nemlendirmek için sürülen aromalı şeker şurubu.',
    'A flavoured sugar syrup brushed onto sponge to keep it moist.',
  ),
  g(
    'Pasta Altlığı',
    'Cake Board',
    'Pastanın üzerinde durduğu sağlam, dekoratif taban.',
    'The sturdy, decorative base on which the cake sits.',
  ),
  g(
    'Bordür',
    'Border / Piping',
    'Pastanın kenarlarına kremayla yapılan dekoratif sıkma desenler.',
    'Decorative piped patterns applied with cream along the cake edges.',
  ),
  g(
    'Macaron',
    'Macaron',
    'Badem unundan yapılan, iki kabuğun arasına krema sürülen Fransız tatlısı.',
    'A French confection of almond-flour shells sandwiched with filling.',
  ),
  g(
    'Buttercream Çiçek',
    'Buttercream Flower',
    'Özel uçlarla tereyağlı kremadan sıkılarak yapılan çiçek motifleri.',
    'Flower motifs piped from buttercream using special nozzles.',
  ),
  g(
    'İzomalt',
    'Isomalt',
    'Cam benzeri, şeffaf süslemeler yapmak için kullanılan şeker türevi.',
    'A sugar substitute used to make glass-like transparent decorations.',
  ),
  g(
    'Pralin',
    'Praline',
    'Karamelize edilmiş fındık veya bademin öğütülmesiyle elde edilen dolgu.',
    'A filling made from ground caramelised hazelnuts or almonds.',
  ),
  g(
    'Krokan',
    'Croquant',
    'Karamel ve kuruyemişle hazırlanan, çıtır dokulu süsleme.',
    'A crunchy decoration made with caramel and nuts.',
  ),
  g(
    'Marzipan',
    'Marzipan',
    'Badem ve şekerden yapılan, şekillendirilebilen tatlı hamur.',
    'A mouldable sweet paste made from almonds and sugar.',
  ),
  g(
    'Temperleme',
    'Tempering',
    'Çikolatanın parlak ve çıtır olması için kontrollü ısıtma-soğutma işlemi.',
    'The controlled heating and cooling of chocolate for a glossy, crisp finish.',
  ),
  g(
    'Lustre Tozu',
    'Lustre Dust',
    'Yenilebilir, metalik parıltı veren dekoratif toz.',
    'An edible decorative dust that adds a metallic shimmer.',
  ),
  g(
    'Genuaz',
    'Genoise',
    'Tereyağsız, çırpılmış yumurtayla kabaran hafif İtalyan pandispanyası.',
    'A light Italian sponge leavened with whipped eggs and no butter.',
  ),
  g(
    'Krem Şanti',
    'Chantilly Cream',
    'Vanilyayla tatlandırılmış, hafifçe şekerli çırpılmış krema.',
    'Lightly sweetened whipped cream flavoured with vanilla.',
  ),
  g(
    'Curd',
    'Curd',
    'Meyve, şeker ve yumurtayla hazırlanan yoğun, ekşimsi dolgu.',
    'A dense, tangy filling made with fruit, sugar and eggs.',
  ),
  g(
    'Krokembuş',
    'Croquembouche',
    'Karamelle birbirine yapıştırılan profiterol kulesinden oluşan Fransız tatlısı.',
    'A French dessert of a tower of profiteroles bound with caramel.',
  ),
  g(
    'Mus',
    'Mousse',
    'Hava kabarcıklarıyla hafifletilmiş, kremamsı ve yumuşak dolgu.',
    'A creamy, soft filling lightened with air bubbles.',
  ),
  g(
    'Sıvama',
    'Crumb Coat',
    'Kırıntıları hapsetmek için sürülen ince ilk krema katmanı.',
    'A thin first layer of frosting applied to trap crumbs.',
  ),
  g(
    'Royal İcing',
    'Royal Icing',
    'Yumurta akı ve pudra şekeriyle yapılan, sertleşen ince dekorasyon kreması.',
    'A hardening decorative icing made with egg white and icing sugar.',
  ),
  g(
    'Şeker Hamuru',
    'Gum Paste',
    'Çabuk sertleşen, ince çiçek ve figürler için ideal şekerli hamur.',
    'A quick-hardening sugar paste ideal for fine flowers and figures.',
  ),
  g(
    'Ombre',
    'Ombre',
    'Bir renkten diğerine yumuşak geçiş yapan tonlama tekniği.',
    'A shading technique with a soft transition from one colour to another.',
  ),
  g(
    'Semifredo',
    'Semifreddo',
    'Yarı dondurulmuş, dondurma kıvamında İtalyan tatlısı.',
    'A semi-frozen Italian dessert with an ice-cream-like texture.',
  ),
  g(
    'Dakuaz',
    'Dacquoise',
    'Fındık veya bademli, çıtır beze tabanlı katman.',
    'A crisp meringue-based layer with hazelnut or almond.',
  ),
  g(
    'Feuilletine',
    'Feuilletine',
    'İnce, çıtır gofret kırıntılarından oluşan dokulu malzeme.',
    'A textured ingredient made of thin, crisp wafer flakes.',
  ),
  g(
    'Namelaka',
    'Namelaka',
    'İpeksi, yoğun kıvamlı bir çikolata kreması türü.',
    'A type of silky, dense-textured chocolate cream.',
  ),
  g(
    'Glaçaj',
    'Glaze / Glaçage',
    'Pastaya ayna gibi parlak bir yüzey veren akışkan kaplama.',
    'A flowing coating that gives the cake a mirror-like glossy surface.',
  ),
  g(
    'Konfi',
    'Confit',
    'Meyvenin şekerle ağır ateşte pişirilmesiyle elde edilen yoğun dolgu.',
    'A dense filling made by slow-cooking fruit with sugar.',
  ),
  g(
    'Streusel',
    'Streusel',
    'Un, tereyağı ve şekerle yapılan ufalanan çıtır üst katman.',
    'A crumbly, crisp topping made with flour, butter and sugar.',
  ),
  g(
    'Pâte à Choux',
    'Pâte à Choux',
    'Profiterol ve ekler yapımında kullanılan hafif hamur.',
    'A light dough used to make profiteroles and éclairs.',
  ),
  g(
    'Bavarua',
    'Bavarois',
    'Jelatinle sabitlenen, kremamsı ve hafif bir muss türü.',
    'A creamy, light type of mousse set with gelatine.',
  ),
  g(
    'Kuvertür Yaprağı',
    'Chocolate Shard',
    'Temperlenmiş çikolatadan yapılan ince, dekoratif çikolata parçası.',
    'A thin, decorative chocolate piece made from tempered chocolate.',
  ),
  g(
    'Naj',
    'Nappage',
    'Meyve tartlarına parlaklık veren şeffaf jel kaplama.',
    'A clear gel glaze that gives fruit tarts their shine.',
  ),
  g(
    'Pistole',
    'Pistolet',
    'Kadifemsi bir doku için çikolata püskürtmede kullanılan teknik.',
    'A technique of spraying chocolate for a velvety texture.',
  ),
  g(
    'Anglez Kreması',
    'Crème Anglaise',
    'Yumurta sarısı, süt ve şekerle yapılan ince vanilyalı sos.',
    'A thin vanilla sauce made with egg yolk, milk and sugar.',
  ),
  g(
    'Pâtissière Kreması',
    'Crème Pâtissière',
    'Pastalarda dolgu olarak kullanılan yoğun pastacı kreması.',
    'A thick pastry cream used as a filling in cakes.',
  ),
  g(
    'Sablé',
    'Sablé',
    'Tereyağı oranı yüksek, ufalanan kıvamlı tart hamuru.',
    'A high-butter, crumbly tart dough.',
  ),
  g(
    'Compote',
    'Compote',
    'Şekerle hafifçe pişirilmiş, parçalı meyve karışımı.',
    'A chunky fruit mixture lightly cooked with sugar.',
  ),
  g(
    'Brûlée',
    'Brûlée',
    'Şekerin pürmüzle karamelize edilmesiyle oluşan çıtır yüzey.',
    'A crisp surface created by caramelising sugar with a torch.',
  ),
  g(
    'Entremet',
    'Entremet',
    'Birden çok dokuyu katmanlayan sofistike modern Fransız pastası.',
    'A sophisticated modern French cake layering multiple textures.',
  ),
  g(
    'Tant pour Tant',
    'Tant pour Tant',
    'Eşit oranda badem ve pudra şekeri karışımı.',
    'An equal-parts mixture of almond and icing sugar.',
  ),
  g(
    'Mirror Glaze',
    'Mirror Glaze',
    'Yüzeyi ayna gibi yansıtan, parlak ve renkli modern kaplama.',
    'A glossy, colourful modern coating with a mirror-like reflective surface.',
  ),
  g(
    'Ombre Sıkma',
    'Ombre Piping',
    'Bir tondan diğerine geçiş yapan kremayla sıkma tekniği.',
    'A piping technique with cream transitioning from one tone to another.',
  ),
  g(
    'Tuile',
    'Tuile',
    'İnce, kıvrımlı ve çıtır dekoratif bisküvi.',
    'A thin, curved and crisp decorative biscuit.',
  ),
  g(
    'Bonbon',
    'Bonbon',
    'İnce çikolata kabuğu içinde yumuşak dolgulu, tek lokmalık şekerleme.',
    'A bite-sized confection with a soft filling in a thin chocolate shell.',
  ),
  g(
    'Pâte Sucrée',
    'Pâte Sucrée',
    'Tatlı tartlar için kullanılan, şekerli ve gevrek hamur.',
    'A sweet, crisp dough used for dessert tarts.',
  ),
];
