'use client';

import { useMemo } from 'react';
import { Text, Float, useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import type { CakeConfig, FlavorKey, SizeKey } from '@/types/cake';

// Real GLTF (.glb) decoration assets, generated by scripts/export-models.mjs.
const MODELS = {
  berry: '/models/berry.glb',
  macaron: '/models/macaron.glb',
  flower: '/models/flower.glb',
  topper: '/models/topper.glb',
} as const;

useGLTF.preload(MODELS.berry);
useGLTF.preload(MODELS.macaron);
useGLTF.preload(MODELS.flower);
useGLTF.preload(MODELS.topper);

type Placement = {
  position: [number, number, number];
  rotation?: [number, number, number];
};

function ringPlacements(count: number, r: number, y: number): Placement[] {
  return Array.from({ length: count }, (_, i) => {
    const a = (i / count) * Math.PI * 2;
    return {
      position: [Math.cos(a) * r, y, Math.sin(a) * r] as [number, number, number],
      rotation: [0, -a, 0] as [number, number, number],
    };
  });
}

/** A single cloned instance of a loaded GLTF scene. */
function GltfClone({
  object,
  scale,
  ...props
}: {
  object: THREE.Object3D;
  scale: number;
} & Placement) {
  const cloned = useMemo(() => {
    const c = object.clone(true);
    c.traverse((o) => {
      o.castShadow = true;
    });
    return c;
  }, [object]);
  return <primitive object={cloned} scale={scale} {...props} />;
}

/** Loads one .glb and scatters cloned instances across the given placements. */
function GltfDeco({
  url,
  placements,
  scale,
}: {
  url: string;
  placements: Placement[];
  scale: number;
}) {
  const { scene } = useGLTF(url);
  return (
    <>
      {placements.map((p, i) => (
        <GltfClone key={i} object={scene} scale={scale} {...p} />
      ))}
    </>
  );
}

const SIZE_RADIUS: Record<SizeKey, number> = {
  small: 0.85,
  medium: 1.15,
  large: 1.5,
};

const TIER_HEIGHT = 0.7;

// Sponge/flavor colours show as a thin band where the frosting "reveals" cake.
const FLAVOR_COLOR: Record<FlavorKey, string> = {
  chocolate: '#5a3825',
  vanilla: '#f3e3c3',
  redvelvet: '#8e2b2b',
  pistachio: '#bcd49a',
  lemon: '#f5e08a',
};

function Decorations({
  config,
  radius,
  topY,
}: {
  config: CakeConfig;
  radius: number;
  topY: number;
}) {
  const { berries, macarons, flowers, topper } = useMemo(
    () => ({
      berries: ringPlacements(10, radius * 0.78, topY + 0.08),
      macarons: ringPlacements(8, radius * 0.82, topY + 0.12),
      flowers: ringPlacements(6, radius * 0.6, topY + 0.14),
      topper: [{ position: [0, topY + 0.5, 0] as [number, number, number] }],
    }),
    [radius, topY],
  );

  return (
    <>
      {config.decorations.includes('berries') && (
        <GltfDeco url={MODELS.berry} placements={berries} scale={0.18} />
      )}
      {config.decorations.includes('macarons') && (
        <GltfDeco url={MODELS.macaron} placements={macarons} scale={0.24} />
      )}
      {config.decorations.includes('flowers') && (
        <GltfDeco url={MODELS.flower} placements={flowers} scale={0.22} />
      )}
      {config.decorations.includes('topper') && (
        <GltfDeco url={MODELS.topper} placements={topper} scale={0.44} />
      )}
    </>
  );
}

export default function CakeModel({ config }: { config: CakeConfig }) {
  const tiers = config.tiers;

  // Compute stacked Y positions; tier 0 is the bottom (largest).
  let y = 0;
  const placed = tiers.map((tier) => {
    const radius = SIZE_RADIUS[tier.size];
    const cy = y + TIER_HEIGHT / 2;
    y += TIER_HEIGHT;
    return { tier, radius, cy };
  });

  const topTier = placed[placed.length - 1];
  const topY = topTier.cy + TIER_HEIGHT / 2;
  const hasDrip = config.decorations.includes('drip');

  return (
    <group position={[0, -y / 2, 0]}>
      {/* Cake plate */}
      <mesh position={[0, -0.08, 0]} receiveShadow>
        <cylinderGeometry args={[SIZE_RADIUS[tiers[0].size] + 0.35, SIZE_RADIUS[tiers[0].size] + 0.45, 0.12, 64]} />
        <meshStandardMaterial color="#e8e0d0" metalness={0.3} roughness={0.4} />
      </mesh>

      {placed.map(({ tier, radius, cy }, i) => (
        <group key={i}>
          {/* Frosted tier */}
          <mesh position={[0, cy, 0]} castShadow receiveShadow>
            <cylinderGeometry args={[radius, radius, TIER_HEIGHT, 64]} />
            <meshStandardMaterial
              color={config.frostingColor}
              roughness={config.frosting === 'fondant' ? 0.25 : 0.7}
              metalness={config.frosting === 'ganache' ? 0.15 : 0}
            />
          </mesh>

          {/* Drip effect ring */}
          {hasDrip && (
            <mesh position={[0, cy + TIER_HEIGHT / 2 - 0.02, 0]}>
              <cylinderGeometry args={[radius + 0.015, radius + 0.015, 0.18, 64, 1, true]} />
              <meshStandardMaterial
                color={config.dripColor || '#C9A84C'}
                side={THREE.DoubleSide}
                roughness={0.3}
              />
            </mesh>
          )}

          {/* Flavor band hint */}
          <mesh position={[0, cy - TIER_HEIGHT / 2 + 0.05, 0]}>
            <cylinderGeometry args={[radius + 0.005, radius + 0.005, 0.06, 64]} />
            <meshStandardMaterial color={FLAVOR_COLOR[tier.flavor]} roughness={0.8} />
          </mesh>
        </group>
      ))}

      {/* Message text on the cake */}
      {config.message.trim() && (
        <Float speed={2} floatIntensity={0.3} rotationIntensity={0}>
          <Text
            position={[0, topTier.cy, topTier.radius + 0.02]}
            fontSize={0.16}
            maxWidth={topTier.radius * 1.6}
            textAlign="center"
            color="#A88A38"
            anchorX="center"
            anchorY="middle"
          >
            {config.message.slice(0, 30)}
          </Text>
        </Float>
      )}

      <Decorations config={config} radius={topTier.radius} topY={topY} />
    </group>
  );
}
